# Generated by Django 2.2 on 2020-07-13 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200703_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newassetapprovalzone',
            old_name='date',
            new_name='data',
        ),
    ]
