# Generated by Django 2.2 on 2020-07-13 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20200713_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='cpy_core_count',
            new_name='cpu_core_count',
        ),
        migrations.RenameField(
            model_name='disk',
            old_name='interface_typ',
            new_name='interface_type',
        ),
    ]
