# Generated by Django 2.2 on 2020-07-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200713_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ram',
            name='slot',
            field=models.CharField(max_length=64, verbose_name='插槽'),
        ),
    ]
